tekis/board/urls.py
from django.conf.urls import url
from django.utils.translation import ugettext_lazy as _

from tekis.board.views import board
from tekis.flatpages.views import flatpage

urlpatterns = [
    url(r"^$", board, name="board"),
    url(r"^(?P<year>\d{4})/$", board, name="board"),
    url(_(r"^older/$"), flatpage,
        name="legacy-boards", kwargs={"url": "legacy-boards"}),
]

tekis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.utils import translation
from django.utils.translation import ugettext as _
from django.contrib.auth.views import login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect

from tekis.flatpages.views import flatpage
from tekis.members.api import MemberDetailsView

admin.site.site_header = settings.SITE_NAME

def index(request):
    return render(request, "index.html")

def members_redir(request, event_id):
    return HttpResponseRedirect(
        "https://members.tko-aly.fi/calendar_events/view/%s/" % event_id
    )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^oauth/', include('tekis.oauth', namespace='oauth2_provider')),
    url(r'^api/v1/', include([
        url('^me/$', MemberDetailsView.as_view(), name="api-member"),
    ])),
    url(r'^event/(?P<event_id>\d+)$', members_redir),
    url(r'^$', index, name="index"),
]

# eagerly populate all localized urls to avoid awkward 404s on deeplinks
cur_language = translation.get_language()
try:
    for lang_code, language in settings.LANGUAGES:
        translation.activate(lang_code)
        urlpatterns.extend([
            url(_(r'^board/'), include('tekis.board.urls')),
            url(_(r'^login/$'), login, name="login", ),
            url(_(r'^logout/$'), logout, name="logout"),
        ])
finally:
    translation.activate(cur_language)

urlpatterns.extend(
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

urlpatterns.extend([
    url(r'^(?P<url>.*)$', flatpage, name='flatpage'),
])

tekis/board/models.py
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _
from django.db import models


class Board(models.Model):
    year = models.IntegerField()

    officers = models.TextField()

    class Meta:
        ordering = ("year",)
        get_latest_by = "year"
        verbose_name = _("Board")
        verbose_name_plural = _("Boards")

    def __unicode__(self):
        return _("Board %(year)s") % {"year": self.year}

ROLE_CHOICES = (
    (0, _("Chairman")),
    (1, _("Treasurer")),
    (2, _("Secretary")),
    (3, _("Vice chairman")),
    (4, _("Board Member")),
    (5, _("Study affairs")),
    (6, _("Communications")),
    (7, _("Corporate affairs")),
    (8, _("RV affairs")),
    (9, _("Freshman affairs")),
    (20, _("First deputy board member")),
    (21, _("Second deputy board member")),
    (22, _("Third deputy board member")),
    (23, _("Fourth deputy board member")),
)


class BoardMember(models.Model):
    board = models.ForeignKey(Board)
    name = models.CharField(max_length=100, verbose_name=_("Name"))
    face = models.ImageField(upload_to="board_faces/%Y/", verbose_name=_("Mugshot"))
    role = models.IntegerField(choices=ROLE_CHOICES, verbose_name=_("Role"))
    contact = models.CharField(max_length=100, default=_("firstname.lastname(at)cs.helsinki.fi"), verbose_name=_("Contact"))

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ("role",)
        verbose_name = _("Board Member")
        verbose_name_plural = _("Board Members")

tekis/members/models.py
from __future__ import unicode_literals
import hashlib

from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.crypto import salted_hmac
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


ROLE_CHOICES = (
    (None, _("Nothing")),
    ("jasenvirkailija", _("Member officer")),
    ("kayttaja", _("Member")),
    ("virkailija", _("Officer")),
    ("yllapitaja", _("Administrator")),
    ("tenttiarkistovirkailija", _("Exam archive officer"))
)

MEMBERSHIP_CHOICES = (
    (None, _("Nothing")),
    ("ei-jasen", _("Non-member")),
    ("erotettu", _("Membership revoked")),
    ("ulkojasen", _("External member")),
    ("jasen", _("Member")),
    ("kannatusjasen", _("Sponsor member")),
    ("kunniajasen", _("Honor member"))
)


class TekisMember(models.Model):
    """Remote member model used for authentication"""
    username = models.CharField(max_length=20)
    name = models.CharField(max_length=255)
    screen_name = models.CharField(max_length=255)
    email = models.EmailField()
    residence = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    hyy_member = models.BooleanField()
    membership = models.CharField(max_length=20, choices=MEMBERSHIP_CHOICES)
    role = models.CharField(max_length=40, choices=ROLE_CHOICES)
    created = models.DateTimeField()
    modified = models.DateTimeField()
    hashed_password = models.CharField(max_length=40)
    salt = models.CharField(max_length=20)
    tktl = models.BooleanField()
    deleted = models.BooleanField()

    def __unicode__(self):
        return self.username

    def check_password(self, raw_password):
        """
        Return a boolean of whether the raw_password was correct.
        """
        czech = hashlib.sha1((
            self.salt
            + getattr(settings, "SITE_LOGIN_SALT", "heiinmpi")
            + raw_password).encode('utf-8')).hexdigest()
        return czech == self.hashed_password

    def save(self, *args, **kwargs):
        raise NotImplementedError("Read-only model!")

    class Meta:
        managed = False
        db_table = "users"


def add_member(role):
    from django.utils.timezone import now
    # testing user creation
    return TekisMember.objects.create(
        username=role,
        name=role,
        screen_name=role,
        email="%s@%s.fi" % (role, role),
        residence="kerava",
        phone=role,
        hyy_member=True,
        membership="jasen",
        role=role,
        created=now(),
        modified=now(),
        hashed_password='bf97b090e2ec03c39dd5e6cde5b48c3fc4b1bc87',
        salt="abc",
        tktl=True,
        deleted=False
    )

tekis/board/views.py
from django.shortcuts import render

from tekis.board.models import Board

def board(request, year=None):
    if year is None:
        board = Board.objects.latest()
    else:
        board = get_object_or_404(Board, year=year)

    return render(request, "board/board.html", {
        "year": board.year,
        "members": board.boardmember_set.all(),
        "officers": board.officers,
        "other_years": Board.objects.values_list("year", flat=True).distinct()
    })

tekis/members/views.py
from django.shortcuts import render

# Create your views here.

tekis/board/templates/board/board.html
{% extends BASE_TEMPLATE %}

{% load i18n %}
{% load markup_tags %}

{% block content %}
<h2>{% blocktrans %}Board {{ year }}{% endblocktrans %}</h2>

<p>
  <a href="{% url "legacy-boards" %}">{% trans "Past boards" %}</a>
  {% for other_year in other_years %}
  |
  {% if other_year == year %}<strong>{{ other_year }}</strong>
  {% else %}
  <a href="{% url "board" other_year %}">{{ other_year }}</a>
  {% endif %}
  {% endfor %}
</p>

<ul class="list-inline">
{% for member in members %}
<li>
  <img src="{{ member.face.url }}" alt="{{ member.name }}">
  <h3>{{ member.name }}
    <br><small>{{ member.get_role_display }}</small>
  </h3>
  <p>{{ member.contact }}</p>
</li>
{% endfor %}
</ul>

<h2>{% blocktrans %}Officers {{ year }}{% endblocktrans %}</h2>

{{ officers|apply_markup:"textile" }}

{% endblock %}

tekis/templates/base.html
<!doctype html>

{% load i18n %}
{% load flatpage_tags %}
{% load staticfiles %}

<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "css/site.css" %}" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% block extra_css %}{% endblock %}

{% block header %}
<title>{{ SITE_NAME }} {% block extra_title %}{% endblock %}</title>
{% endblock %}

{% block menu %}
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">{{ SITE_NAME }}</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar">
        <span class="sr-only">{% trans "Toggle navigation" %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
	<li>
	  <a href="{% mainpage_link_for_category 1 %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	    {% trans "Association" %}
	    <span class="caret"></span>
	  </a>
	  <ul class="dropdown-menu">
	    <li><a href="{% url "board" %}">{% trans "Board" %}</a></li>
	    {% menu_for_category 1 %}
	  </ul>
	</li>
	<li>
	  <a href="{% mainpage_link_for_category 2 %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	    {% trans "Activities" %}
	    <span class="caret"></span>
	  </a>
	  <ul class="dropdown-menu">
	    {% menu_for_category 2 %}
	  </ul>
	</li>
	{% menu_for_category 0 %}
      </ul>
      <form action="{% url 'set_language' %}" method="post">
	{% csrf_token %}
      <ul class="nav navbar-nav navbar-right">
	<li>
	  {% get_current_language as LANGUAGE_CODE %}
	  {% get_available_languages as LANGUAGES %}
	  {% get_language_info_list for LANGUAGES as languages %}
	    <input name="next" type="hidden" value="{{ redirect_to }}" />
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	      <span class="glyphicon glyphicon-cog" aria-label="{% trans "Options" %}"></span>
	      <span class="caret"></span>
	    </a>
	    <ul class="dropdown-menu">
	      {% if user.is_authenticated %}
	      <li class="dropdown-header">{% blocktrans with user.first_name as name %}Hello, <strong>{{ name }}</strong>{% endblocktrans %}</li>
	      {% if user.is_staff %}
	      <li><a href="{% url "admin:index" %}">{% trans "Site Admin" %}</a></li>
	      {% endif %}
	      <li><a href="{% url "oauth2_provider:index" %}">{% trans "Single Sign On" %}</a></li>
	      <li><a href="{% url "logout" %}">{% trans "Log out" %}</a></li>
	      {% else %}
	      <li class="dropdown-header">{% trans "Not logged in" %}</li>
	      <li><a href="{% url "login" %}">{% trans "Member login" %}</a></li>
	      <li><a href="http://members.tko-aly.fi/users/add">{% trans "Become a Member" %}</a></li>
	      {% endif %}
	      <li class="dropdown-header always-dark">{% trans "Select Language" %}</li>
	      {% for language in languages %}
	      <li class="always-dark">
		{% if language.code == LANGUAGE_CODE %}
		<button class="btn btn-link-settings btn-link">{{ language.name_local|capfirst }} ({{ language.code }})</button>
		{% else %}
		<button name="language" value="{{ language.code }}" class="btn btn-link-settings btn-link">
		  {{ language.name_local|capfirst }} ({{ language.code }})
		</button>
		{% endif %}
	      </li>
	      {% endfor %}
	    </ul>
	</li>
      </ul>
      </form>
    </div>
  </div>
</nav>
{% endblock %}

<div class="container">
  <div id="content">
    {% block content %}{% endblock %}
  </div>
</div>


<div id="footer">
  <div class="container" id="sponsor">
    <h3>{% trans "Sponsors" %}</h3>

    <div id="sponsor-bag">
      {% show_sponsors %}
    </div>
  </div>

  <div class="container" id="footer-container">
    {% block footer %}
    <div class="row">
      <div class="col-md-4">
	<h3>{% trans "Mail" %}</h3>
	TKO-äly ry / TKTL<br>
	PL 68<br>
	00014 Helsingin yliopisto
	<h3>{% trans "Company ID (Y-tunnus)" %}</h3>
	1978827-2<br>
      </div>
      <div class="col-md-4">
	<h3>{% trans "E-mail" %}</h3>
	hallitus (ät) tko-aly.fi
	<h3>{% trans "Chairman" %}</h3>
	pj ät tko-aly.fi
      </div>
      <div class="col-md-4">
	<h3>{% trans "Phone to student room Gurula" %}</h3>
	+358-50-4480186
	<h3>{% trans "Bank Accounts" %}</h3>
	{% trans "Main Account" %} FI28 3939 0001 3001 02<br>
	{% trans "RV Account" %} FI50 3939 0001 3000 94<br>
	BIC SBANFIHH
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-4">
	<p>{% blocktrans %}Content &copy; {{ SITE_NAME }} and contributors.{% endblocktrans %}</p>

	<p>{% blocktrans with "https://github.com/hylje/tekis" as source_link %}The website software is free software and <a href="{{ source_link }}">is available on Github.</a> Feel free to fork it for your own association!{% endblocktrans %}</p>
      </div>
    </div>
    {% endblock %}
  </div>
</div>

<script src="{% static "js/jquery-1.12.0.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
{% block extra_js %}{% endblock %}

tekis/templates/base_retro.html
<!doctype html>
<!--?xml version='1.0' encoding='utf-8' ?-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

{% load i18n %}
{% load flatpage_tags %}
{% load staticfiles %}

<head>
{% block header %}
  <title>{{ SITE_NAME }}</title>
{% endblock %}

<link href="{% static "retro/stylesheets/reset.css" %}" rel="stylesheet">
<link href="{% static "retro/stylesheets/default.css" %}" rel="stylesheet">
<link href="{% static "retro/favicon.ico.png" %}" rel="shortcut icon" type="image/x-icon">

{% get_current_language as LANGUAGE_CODE %}
<meta content="{{ LANGUAGE_CODE }}" http-equiv="content-language">
<meta content="TKO-äly ry" name="author">
<meta content="TKO-äly ry - Helsingin yliopiston tietojenkäsittelytieteen opiskelijoiden ainejärjestö" name="description">
<meta content="http://tko-aly.fi/images/logo-150.png" property="og:image">
{% block extra_css %}{% endblock %}
</head>

<body>
  <div id="wrapper">
    {% block menu %}
      <div id="menu">
	<form method="post" action="{% url 'set_language' %}">
	  {% csrf_token %}
	  <ul>
	  <li class="border">
	    <a href="/">{% trans "Main page" %}</a>
	  </li>
	  <li>
	    <a href="{% mainpage_link_for_category 1 %}">
	      {% trans "Association" %}
	    </a>
	  </li>
	  {% if current_category == 1 %}
	  <li class="overlap submenu">
	    <ul class="sub">
	      <li><a href="{% url "board" %}">{% trans "Board" %}</a></li>
	      {% menu_for_category 1 %}
	      <li class="overlap"></li>
	    </ul>
	  </li>
	  {% endif %}
	  <li>
	    <a href="{% mainpage_link_for_category 2 %}">
	      {% trans "Activities" %}
	    </a>
	  </li>
	  {% if current_category == 2 %}
	  <li class="overlap submenu">
	    <ul class="sub">
	      {% menu_for_category 2 %}
	      <li class="overlap"></li>
	    </ul>
	  </li>
	  {% endif %}
	  {% menu_for_category 0 %}
	  {% get_available_languages as LANGUAGES %}
	  {% get_language_info_list for LANGUAGES as languages %}
	  {% for language in languages %}
	    {% if language.code != LANGUAGE_CODE %}
	      <li class="border">
		<button name="language" value="{{ language.code }}">
		  {{ language.name_local|capfirst }} ({{ language.code }})
		</button>
	      </li>
	    {% endif %}
	  {% endfor %}
	  {% block extra_menu %}{% endblock %}
	  <li class="overlap"></li>
	</ul>
	</form>
      </div>
    {% endblock %}

  <div id="content">
    <div id="header">
      <h1>
	<a href="/">
	  <span class="whitetext">
	    Helsingin yliopiston tietojenkäsittelytieteen
	    <br>
	  </span>
	  opiskelijoiden ainejärjestö
	</a>
      </h1>
    </div>
    <h1 id="title">{% block extra_title %}{% endblock %}</h1>
    <div id="text">
      {% block content %}
      {% endblock %}
    </div>
    <div id="sponsor">
      <h1>{% trans "Sponsors" %}</h1>
      {% show_sponsors %}
    </div>
    <div id="footer">
      <div class="section">
	<h1>{% trans "Mail" %}</h1>
	TKO-äly ry / TKTL<br>
	PL 68<br>
	00014 Helsingin yliopisto
	<h1>{% trans "Company ID (Y-tunnus)" %}</h1>
	1978827-2<br>
      </div>
      <div class="section">
	<h1>{% trans "E-mail" %}</h1>
	hallitus (ät) tko-aly.fi
	<h1>{% trans "Chairman" %}</h1>
	pj ät tko-aly.fi
      </div>
      <div class="section">
	<h1>{% trans "Phone to student room Gurula" %}</h1>
	+358-50-4480186
	<h1>{% trans "Bank Accounts" %}</h1>
	{% trans "Main Account" %} FI28 3939 0001 3001 02<br>
	{% trans "RV Account" %} FI50 3939 0001 3000 94<br>
	BIC SBANFIHH
      </div>
      <div class="overlap"></div>
    </div>
  </div>
</body>

tekis/templates/index.html
{% extends BASE_TEMPLATE %}

{% load i18n %}
{% load flatpage_tags %}
{% load staticfiles %}

{% block extra_title %}{% trans "Welcome" %}{% endblock %}

{% block content %}

{% embed_flatpage "" %}

{% endblock %}

tekis/templates/oauth2_provider/application_detail.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}

{% block content %}
<h2>{% blocktrans with name=application.name %}OAuth Application: {{ name }}{% endblocktrans %}</h2>


  <p>
    {% blocktrans %}If you lose the secret, please delete and recreate
    the app.{% endblocktrans %}
  </p>

  <p>
    <strong>{% trans "Client ID:" %}</strong> <tt>{{ application.client_id }}</tt>
  </p>

  <p>
    <strong>{% trans "Client Secret:" %}</strong>
    <div>
      <textarea rows="3" cols="60" disabled="disabled">{{ application.client_secret }}</textarea>
    </div>
  </p>

  <p>
    <strong>{% trans "Client type:" %}</strong>
    <tt>{{ application.client_type }}</tt>
  </p>

<p>
  <strong>{% trans "Authorization Grant Type:" %}</strong>
  <tt>{{ application.authorization_grant_type }}</tt>
</p>


<div class="btn-toolbar">
  <a class="btn" href="{% url "oauth2_provider:list" %}">{% trans "Go Back" %}</a>
  <a class="btn btn-primary" href="{% url "oauth2_provider:update" application.id %}">{% trans "Edit" %}</a>
  <a class="btn btn-danger" href="{% url "oauth2_provider:delete" application.id %}">{% trans "Delete" %}</a>
</div>

{% endblock %}

tekis/templates/oauth2_provider/application_form.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}

{% block content %}
<form class="" method="post" action="{% block app-form-action-url %}{% url 'oauth2_provider:update' application.id %}{% endblock app-form-action-url %}">
  <h2>
    {% block app-form-title %}
    {% blocktrans with name=application.name %}Edit application {{ name }}{% endblocktrans %}
    {% endblock app-form-title %}
  </h2>

  {% csrf_token %}

  <div class="control-group {% if form.non_field_errors %}error{% endif %}">
    {% for error in form.non_field_errors %}
    <span class="help-inline">{{ error }}</span>
    {% endfor %}
  </div>

  {% for field in form %}
  {% include "snippets/form_group.html" %}
  {% endfor %}

  <div class="control-group">
    <div class="controls">
      <a class="btn" href="{% block app-form-back-url %}{% url "oauth2_provider:detail" application.id %}{% endblock app-form-back-url %}">
        {% trans "Go Back" %}
      </a>
      <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
    </div>
  </div>
</form>
{% endblock %}

tekis/templates/oauth2_provider/base.html
{% extends BASE_TEMPLATE %}

tekis/templates/oauth2_provider/index.html
{% extends "oauth2_provider/base.html" %}

{% load i18n %}

{% block content %}
<h2>{% trans "Single Sign On" %}</h2>

{% if user.is_authenticated %}
<p>{% blocktrans %}The {{ SITE_NAME }} single sign on service allows members to access association and affiliate services with a single login. You can manage your access or create your own services here.{% endblocktrans %}</p>
<ul>
  <li><a href="{% url "oauth2_provider:list" %}">{% trans "Applications" %}</a></li>
  <li><a href="{% url "oauth2_provider:authorized-token-list" %}">{% trans "Access Tokens" %}</a></li>
</ul>
{% else %}
<p>{% blocktrans %}The {{ SITE_NAME }} single sign on service allows members to access association and affiliate services with a single login. Members can manage their SSO access or create their own services here.{% endblocktrans %}</p>

{% url 'login' as login_url %}
<p>{% blocktrans %}You are currently not logged in as a member, but you can still browse the API reference below. Members can <a href="{{ login_url }}">log in here</a>.{% endblocktrans %}</p>
{% endif %}
<h3>{% trans "API reference" %}</h3>

<p>{% blocktrans %}SSO is implemented using OAuth2.{% endblocktrans %}</p>

<p>
  {% with "http://tutorials.jenkov.com/oauth2/endpoints.html" as tutorial_url %}
  {% with "http://django-oauth-toolkit.herokuapp.com/consumer/" as consumer_url %}
  {% blocktrans %}Check out OAuth tutorials, RFC, etc. for more details about OAuth 2 protocol views. <a href="{{ tutorial_url }}">This one might be a decent tutorial</a>. You can fiddle with the API using <a href="{{ consumer_url }}">this sample consumer app</a> and the endpoint URLs given below.{% endblocktrans %}
  {% endwith %}
  {% endwith %}
</p>

<p>
  {% blocktrans %}Authorization code flow is supported. Supported scopes are <tt>read</tt> and <tt>write</tt>.{% endblocktrans %}
</p>

<p>
  {% blocktrans %}You can also test your authentication code on a clone of this site. The link to this site's source code should be provided in the footer.{% endblocktrans %}
</p>

<p>{% blocktrans %}To access authenticated APIs, a Bearer Token is supported.{% endblocktrans %}

<h5>HTTP Header:</h5>
<pre>
  Authorization: Bearer &lt;TOKEN-BLOB&gt;
</pre>

<div>
  <h4>OAuth Authorize</h4>
  <p><tt>GET {{ SITE_URL }}{% url 'oauth2_provider:authorize' %}</tt></p>
  <p>{% trans "Asks the user to authorize the app" %}</td>
</div>

<div>
  <h4>OAuth Token</h4>
  <p><tt>POST {{ SITE_URL }}{% url 'oauth2_provider:token' %}</tt></p>
  <p>{% trans "Exchange grant for token" %}</p>
</div>

<div>
  <h4>OAuth Token Revoke</h4>
  <p><tt>POST {{ SITE_URL }}{% url 'oauth2_provider:revoke-token' %}</tt></p>
  <p>{% trans "Revoke a token" %}</p>
</div>

<div>
  <h4>Member info</h4>
  <p><tt>GET {{ SITE_URL }}{% url 'api-member' %}</tt></p>
  <p>{% trans "Exchange a token for user information as JSON." %}</p>
<pre>{
  "content": {
    "username": "jouluporo"
    "real_name": "Petteri Punakuono"
    "role": "jasen"
  }
}</pre>
  <p><tt>role</tt>: [<tt>"jasen"</tt>, <tt>"virkailija"</tt>, <tt>"yllapitaja"</tt>]</p>
</div>
{% endblock %}

tekis/templates/snippets/form_group.html
{% load i18n %}
{% if field.is_hidden %}
{{ field }}
{% else %}
<div class="form-group {% if field.errors %}has-feedback has-error{% endif %}">
  <label for="{{ field.auto_id }}">
    {{ field.label }}
    {% if field.field.required %}<br><small>{% trans "Required" %}</small>{% endif %}
  </label>
  {{ field.errors }}
  {{ field }}
  <p class="help-text">{{ field.help_text|safe }}</p>
</div>
{% endif %}